### ISSUE TITLE
Python 3.10 build pytest fails due to hardcoded python3.9

### ISSUE THREAD

**Issue by snacsnoc** [dev-sushi/sushi#14]
This is due to setting the default interpreter to `python3.9`: https://github.com/dev-sushi/sushi/blob/main/tests/test_execute.py#L36

```python
E               FileNotFoundError: [Errno 2] No such file or directory: 'python3.9'

/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/subprocess.py:1847: FileNotFoundError
=========================== short test summary info ============================
FAILED test_execute.py::TestExecute::test_noarg - FileNotFoundError: [Errno 2] No such file or directory: 'python3.9'
```
See latest Github build log here: https://github.com/dev-sushi/sushi/actions/runs/4376862394/jobs/7659572167

Possible solutions:

1. Use `python3` for most compatibility and hope Github actions has a symlink from `python3.10` to `python3.
2. Specify the interpreter with `pytest`

```
pytest -p python3 --python=python3.10
```
3. Set environment variable path
```
export PYTEST_PYTHON=/path/to/python3.10
pytest
```

**Comment by ksawery29** [comment]
I forgot to commit that changes to just `python`. We can use `python3` though

**Comment by ksawery29** [comment]
@snacsnoc I will close this issue since as I commented I just forgot to revert python3.9 to python.

**Comment by snacsnoc** [comment]
@ksawery29 Consider using `python3` instead. `python` on some systems may refer to Python 2, albeit Python 2 has already gone EOL. See [PEP 394](https://peps.python.org/pep-0394/)

Debian stable (11) ships with Python 2.7 and `python` refers to Python 2.7:

```bash
[easto@cupcake][~]$ cat /etc/debian_version 
11.6
[easto@cupcake][~]$ python -V
Python 2.7.18
[easto@cupcake][~]$ python3 -V
Python 3.9.2
```

Ubuntu as of 20.04 has removed Python 2.7, and Fedora has Python 3 as default since version 23.
Resources:
https://wiki.debian.org/Python
https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default
https://fedoraproject.org/wiki/Changes/Python_3_as_Default

**Comment by ksawery29** [comment]
Thanks, I will try to change it in tests.
