### ISSUE TITLE
Saved indexed function file uses positional arguments instead of keyword arguments

### ISSUE THREAD

**Issue by snacsnoc** [dev-sushi/sushi#18]
With this commit https://github.com/dev-sushi/sushi/commit/38afe1e67b2ce772f1a01eb15a4141f2052223af sushi now writes to the indexed function file using positional arguments.
Example:
```python
from sushipy.execute import Execute
def helloWorld(number):	Execute('main.hpp', number)
```

Previously, sushi used a keyword argument to specify the file, and positional arguments for any input arguments to be passed.
Example:
```python
from sushipy.execute import Execute
def helloWorld(number):	Execute(file='main.hpp', number)

```
 With this method, sushi will fail as positional args must be declared before keyword args. 
 
Currently sushi does not accept:
 ```python
 from sushipy.execute import Execute
def helloWorld(number):	Execute(number, file='main.hpp')

 ```
 
 Resources: 
 https://peps.python.org/pep-3102/

**Comment by ksawery29** [comment]
I will look into this tomorrow.

**Comment by ksawery29** [comment]
It's working now. I will do a little bit of tweaking and then commit it.

**Comment by ksawery29** [comment]
Turns out it can't be pushed yet because of some failing stuff that I will need to fix. I don't have much time today so I will finish it tomorrow. Sorry about that!

**Comment by snacsnoc** [comment]
No problem! I can take a look at this later tonight. 

I know sushi used keyword args before my PR, but let me ask you if this is something we really need? 

Positional args work fine (for now), although it would be nice having keyword args in the generated code to make reading code a bit easier. 

Could we potentially use keyword arguments to pass the arguments to the function? Eg 'Execute(file='main.hpp',args=arg_list)'

**Comment by ksawery29** [comment]
To be honest, we don't really need it and can move to other things that are planned. But if it's really important it could be done in few minutes.

**Comment by snacsnoc** [comment]
> To be honest, we don't really need it and can move to other things that are planned. But if it's really important it could be done in few minutes.

That's understandable, this feature may be more trouble than it's worth if there's others things to fix. I don't think it's necessary at this point but it's up to you.

**Comment by ksawery29** [comment]
I will close this issue and return tomorrow to developing other features for sushi.
