### ISSUE TITLE
Add better logging system

### ISSUE THREAD

**Issue by ksawery29** [dev-sushi/sushi#21]
As the title says, sushi needs to help users understand what is going on by adding more logs. 
This is just a future idea.

**Comment by snacsnoc** [comment]
@ksawery29 Did you have anything in mind? sushi could be more verbose when configuring, saving & executing functions. Perhaps we can include the function names and arguments passed when sushi is running. We could also add a `VERBOSE` setting in sushi.conf to turn off/on verbose printing/logging.

**Comment by ksawery29** [comment]
That's what I wanted to add but that pytest error slowed me. I want to add something like verbose mode as you said and display everything what it is doing.
