### ISSUE TITLE
index.py does not print 'saving' message

### ISSUE THREAD

**Issue by snacsnoc** [dev-sushi/sushi#25]
With the addition of `end="\r"` to this [line](https://github.com/dev-sushi/sushi/blob/main/src/sushipy/index.py#LL110C9-L110C9), sushi does not print the "saving functions" message. This may be terminal specific, but this does not work for me in my IDE terminal (PyCharm) or terminal window (Tabby, Mac OS).

Output:
```
(venv) (base) easto@Eastons-MacBook-Air math-c % python app.py
sushi   saved indexed functions                                                                                                                  
-420735.392546
itt_add() took 0.3960579169999999 seconds
10%                                                                                                                                                                         
```

When I remove `, end="\r"` from index.py:
```
(venv) (base) easto@Eastons-MacBook-Air math-c % python app.py
sushi   saving indexed functions (lib/main.h)                                                                                                    
sushi   saving indexed functions (lib/main.h)                                                                                                    
sushi   saved indexed functions                                                                                                    
-420735.392546
itt_add() took 0.20237095900000002 seconds
10%                                                                                                                                                                         (venv) (base
```

**Comment by ksawery29** [comment]
It's probably because files are saving so fast that you can't even see it. I created it so old messages about saving are being overwritten by new ones (to reduce spam when sushi needs to save bunch of files). We could get rid of it or disable it only for verbose mode.

**Comment by snacsnoc** [comment]
No, it does not print the 'saving' message with `,end="\r"` added to the end of the rich_print(). 

I have begun working on a verbose print mode, controlled by the config file. I will submit a PR within the next day or two, it will at least get us to a working state.

**Comment by ksawery29** [comment]
Thanks for helping create verbose mode! Can you open the pull request as draft earlier so I can also contribute to it?

**Comment by snacsnoc** [comment]
@ksawery29  Great idea, I'll do that
