### ISSUE TITLE
Rewrite tests

### ISSUE THREAD

**Issue by ksawery29** [dev-sushi/sushi#27]
This will fix the pytest issue forever.

**Comment by snacsnoc** [comment]
It seems to me the tests fail on Github Actions. I can't seem to recreate the same error that the Github Action produces.

**Comment by ksawery29** [comment]
@snacsnoc As I mentioned [here](https://github.com/dev-sushi/sushi/pull/28#issuecomment-1484171949) the issue still isn't fixed. I think we will actually need to rewrite all tests or modify sushi to be more "ci friendly". I will look into this tomorrow or later today.

**Comment by ksawery29** [comment]
Probably it's the last update because I found the error. For some reason, it can't find `utils` module. Strange...
```
from utils.verbose_print import verbose_print
ModuleNotFoundError: No module named 'utils'
```

I will need to look into this

**Comment by ksawery29** [comment]
[Fixed!](https://github.com/dev-sushi/sushi/actions/runs/4546517821/jobs/8015241818)
